spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/skb_bank
    username: postgres
    password: admin

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: your-super-secret-key
  expiration: 86400000

frontend:
  url: http://localhost:5173